name: CI

on: [push]

jobs:
  format-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16.x
      - run: npm ci
      - run: npm run format-check

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16.x
      - run: npm ci
      - run: npm run test
      - uses: codecov/codecov-action@v3

  deploy-site:
    runs-on: ubuntu-latest
    needs: [test, format-check]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16.x
      - run: npm ci
      - run: npm run build:web
      - run: npm run build:node
      - run: npm link
      - name: Download demo input files
        run: |
          curl -s -L "https://drive.google.com/uc?export=download&confirm=yes&id=${{ secrets.GDRIVE_DEMO_ID }}" -o export.zip
          unzip -qq export.zip -d export
      - name: Generate demo report
        run: |
          chat-analytics --input export/*.json --output dist_web/demo.html --demo
      - name: Publish
        uses: cloudflare/pages-action@1
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          projectName: chat-analytics
          directory: dist_web
