name: Publish

#on:
#  push:
#    tags:
#      - v*

# for testing
on: [push]


jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16.x
      - run: npm ci
      - run: npm run build:web
      - run: npm run build:node
      - run: npm pack
